package handler

import "net/http"

// RegisterRoutes 把所有 API 与页面路由注册到 mux
func (s *Server) RegisterRoutes(mux *http.ServeMux) {
	// API
	mux.HandleFunc("POST /api/register", s.register)
	mux.HandleFunc("POST /api/login", s.login)
	mux.HandleFunc("POST /api/logout", s.logout)
	mux.HandleFunc("GET /api/me", s.me)
	mux.HandleFunc("POST /api/me/update", s.updateMe)
	mux.HandleFunc("POST /api/me/password", s.changePassword)
	mux.HandleFunc("POST /api/me/ageverify/request", s.requestAgeVerify)
	mux.HandleFunc("POST /api/me/official/request", s.requestOfficialVerify)
	mux.HandleFunc("GET /api/me/favorites", s.myFavorites)
	mux.HandleFunc("GET /api/me/history", s.myHistory)
	mux.HandleFunc("DELETE /api/me/history/{id}", s.deleteHistory)
	mux.HandleFunc("DELETE /api/me/history", s.clearHistory)
	mux.HandleFunc("POST /api/me/dislike", s.dislike)
	mux.HandleFunc("DELETE /api/me/dislike", s.removeDislike)
	mux.HandleFunc("GET /api/feed", s.feed)
	mux.HandleFunc("GET /api/users/search", s.userSearch)
	mux.HandleFunc("POST /api/report/{target}/{id}", s.report)
	mux.HandleFunc("POST /api/notes", s.createNote)
	mux.HandleFunc("GET /api/notes/{id}", s.noteDetail)
	mux.HandleFunc("PUT /api/notes/{id}", s.updateNote)
	mux.HandleFunc("DELETE /api/notes/{id}", s.deleteNote)
	mux.HandleFunc("POST /api/notes/{id}/like", s.like)
	mux.HandleFunc("POST /api/notes/{id}/favorite", s.favorite)
	mux.HandleFunc("POST /api/notes/{id}/pin", s.pinNote)
	mux.HandleFunc("POST /api/notes/{id}/comment", s.comment)
	mux.HandleFunc("POST /api/comments/{id}/like", s.commentLike)
	mux.HandleFunc("DELETE /api/comments/{id}", s.deleteComment)
	mux.HandleFunc("GET /api/messages", s.messages)
	mux.HandleFunc("GET /api/messages/unread", s.messageUnreadCount)
	mux.HandleFunc("GET /api/messages/with/{id}", s.messageThread)
	mux.HandleFunc("POST /api/messages/send", s.messageSend)
	mux.HandleFunc("GET /api/user/{id}", s.userInfo)
	mux.HandleFunc("GET /api/user/{id}/notes", s.userNotes)
	mux.HandleFunc("POST /api/user/{id}/follow", s.follow)
	mux.HandleFunc("GET /api/user/{id}/followers", s.userFollowers)
	mux.HandleFunc("GET /api/user/{id}/following", s.userFollowing)
	mux.HandleFunc("GET /api/tag/{tag}/notes", s.tagNotes)
	mux.HandleFunc("GET /api/tags", s.hotTags) // 热门标签 top12（搜索页快捷入口）
	mux.HandleFunc("GET /api/uid/{uid}", s.userByUid)
	mux.HandleFunc("POST /api/friends/request", s.friendRequest)
	mux.HandleFunc("GET /api/friends/requests", s.friendRequests)
	mux.HandleFunc("POST /api/friends/requests/{id}/accept", s.friendAccept)
	mux.HandleFunc("POST /api/friends/requests/{id}/reject", s.friendReject)
	mux.HandleFunc("GET /api/friends", s.friendList)
	mux.HandleFunc("DELETE /api/friends/{id}", s.friendRemove)
	mux.HandleFunc("POST /api/drafts", s.saveDraft)
	mux.HandleFunc("GET /api/drafts", s.listDrafts)
	mux.HandleFunc("DELETE /api/drafts/{id}", s.deleteDraft)
	mux.HandleFunc("GET /api/notifications", s.notifications)
	mux.HandleFunc("POST /api/notifications/read", s.notificationsReadAll)
	mux.HandleFunc("POST /api/notifications/{id}/read", s.notificationRead)
	mux.HandleFunc("POST /api/upload", s.upload)
	mux.HandleFunc("POST /api/upload/any", s.uploadAny)
	mux.HandleFunc("GET /api/admin/stats", s.adminStats)
	mux.HandleFunc("GET /api/admin/pending", s.adminPending)
	mux.HandleFunc("GET /api/admin/users", s.adminUsers)
	mux.HandleFunc("POST /api/admin/users/{id}/approve", s.adminApprove)
	mux.HandleFunc("POST /api/admin/users/{id}/reject", s.adminReject)
	mux.HandleFunc("POST /api/admin/users/{id}/ban", s.adminBanUser)
	mux.HandleFunc("POST /api/admin/users/{id}/reset-password", s.adminResetPassword)
	mux.HandleFunc("POST /api/admin/users/batch", s.adminBatchUsers)
	mux.HandleFunc("POST /api/admin/users/{id}/ageverify", s.adminAgeVerify)
	mux.HandleFunc("POST /api/admin/users/{id}/ageverify-reject", s.adminRejectAgeVerify)
	mux.HandleFunc("GET /api/admin/users/ageverify-pending", s.adminAgeVerifyPending)
	mux.HandleFunc("POST /api/admin/users/{id}/official", s.adminOfficialVerify)
	mux.HandleFunc("POST /api/admin/users/{id}/official-reject", s.adminRejectOfficialVerify)
	mux.HandleFunc("GET /api/admin/users/official-pending", s.adminOfficialPending)
	mux.HandleFunc("GET /api/admin/notes", s.adminNotes)
	mux.HandleFunc("POST /api/admin/notes/{id}/review", s.adminReviewNote)
	mux.HandleFunc("POST /api/admin/notes/{id}/reject", s.adminRejectNote)
	mux.HandleFunc("POST /api/admin/notes/{id}/remove", s.adminRemoveNote)
	mux.HandleFunc("POST /api/admin/notes/purge-old", s.adminPurgeOldNotes)
	mux.HandleFunc("DELETE /api/admin/notes/{id}/purge", s.adminPurgeNote)
	mux.HandleFunc("GET /api/admin/comments", s.adminComments)
	mux.HandleFunc("POST /api/admin/comments/{id}/delete", s.adminDeleteComment)
	mux.HandleFunc("GET /api/admin/reports", s.adminReports)
	mux.HandleFunc("POST /api/admin/reports/{id}/resolve", s.adminResolveReport)

	// 页面（带登录/管理员门禁）
	mux.HandleFunc("GET /login", s.Page("login.html", "public"))
	mux.HandleFunc("GET /register", s.Page("register.html", "public"))
	mux.HandleFunc("GET /note", s.Page("note.html", "auth"))
	mux.HandleFunc("GET /publish", s.Page("publish.html", "auth"))
	mux.HandleFunc("GET /profile", s.Page("profile.html", "auth"))
	mux.HandleFunc("GET /search", s.Page("search.html", "auth"))
	mux.HandleFunc("GET /notifications", s.Page("notifications.html", "auth"))
	mux.HandleFunc("GET /followers", s.Page("followers.html", "auth"))
	mux.HandleFunc("GET /friends", s.Page("friends.html", "auth"))
	mux.HandleFunc("GET /tag", s.Page("tag.html", "auth"))
	mux.HandleFunc("GET /drafts", s.Page("drafts.html", "auth"))
	mux.HandleFunc("GET /messages", s.Page("messages.html", "auth"))
	mux.HandleFunc("GET /admin", s.Page("admin/index.html", "admin"))
	mux.HandleFunc("GET /admin/", s.Page("admin/index.html", "admin"))
	// 根路径作为兜底（更具体的 /css/、/uploads/、/api/* 模式优先匹配）
	mux.HandleFunc("/", s.Page("index.html", "auth"))
}
